name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn v3
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Install Node packages
        uses: ./.github/actions/yarn-nm-install

      - name: Run Prettier
        run: yarn prettier --check .

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn v3
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Install Node packages
        uses: ./.github/actions/yarn-nm-install

      - name: Run ESLint
        run: yarn eslint .
